### ISSUE TITLE
Add HTTP Proxy Support with TLS for Upstream Connections

### ISSUE THREAD

**Issue by hippalus** [hippalus/umay#7]
# Add HTTP Proxy Support with TLS for Upstream Connections

## **Objective**

Implement an HTTP proxy that supports HTTP/2 by default but can downgrade to HTTP/1.1. 
Add TLS client support for upstream connections, allowing re-encryption when connecting to secure upstream servers (e.g., HTTPS, MQTT over TLS or any TCP over TLS).

### **Tasks**

- [ ] **HTTP Proxy Implementation**  
- [ ] **TLS Client for Upstream Connections** 
- [ ] **Support HTTP/2 with the ability to downgrade to HTTP/1.1 based on client capabilities** 
- [ ] **Support features like header manipulation, filtering, and rate limiting**
